resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/hajimeni/flight-school
    branch: master
- name: build-script-repo
  type: s3
  source:
    bucket: daemonby-app-hosting
    regexp: infra/ci/.*
    region_name: ap-northeast-1
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
jobs:
- name: test-app
  plan:
  - aggregate:
    - get: flight-school
      trigger: true
    - get: build-script-repo
  - task: tests
    file: build-script-repo/infra/ci/build.yml
