resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/hajimeni/flight-school
    branch: master
- name: dmb-infra-concourse
  type: s3
  source:
    bucket: dmb-infra-concourse
    region_name: ap-northeast-1
    regexp: scripts/build.yml
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - get: dmb-infra-concourse
  - task: tests
    file: dmb-infra-concourse/scripts/build.yml
